Makes PageHeader sticky
NASA-IMPACT/nasa-apt-frontend pull request #347
Opened 2022-03-23 12:03 UTC by oliverroick

Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/472; addressing "Once users have found their information, users are able to quickly navigate to somewhere else in the app"

I figured the most straightforward way to deal with this is to make the page header sticky and ensure that the in-page header always sits below the page header. 

<img width="1525" alt="Screenshot 2022-03-23 at 11 59 20" src="https://user-images.githubusercontent.com/159510/159694596-bece5d82-d896-4803-921d-624b14fbcc35.png">

The only drawback is that this affects the whole app, so we're losing a bit of screen real estate everywhere but I feel this is an ok compromise. 

cc: @aboydnw

2022-03-23 12:03 UTC, oliverroick commented on app/assets/scripts/styles/inpage.js
> +  top: calc(40px + 0.75rem * 2);
@danielfdsilva There might be a better way to calculate this using UI-library functions

2022-03-24 10:59 UTC, danielfdsilva requested changes
Having the whole header sticky messes with the calculations done in the ATBD view to position the sidebar TOC.
![Screen Shot 2022-03-24 at 10 56 27](https://user-images.githubusercontent.com/1090606/159901782-35c89c56-d2bb-48be-82db-0ab605f0d45d.png)

This is obviously fixable, but as you say it makes us loose screen real estate.
I'm wondering if a floating "go to top" button wouldn't be a better compromise. If we add a table of contents at the beginning of the document, this is also a quicker way to reach it. @aboydnw thoughts? and maybe @ricardoduplos for a quick UX consult

2022-03-24 12:16 UTC, oliverroick commented
Maybe what I did in https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/346 is already enough. The change includes back-to-top links after each section

2022-03-24 15:43 UTC, danielfdsilva commented
@oliverroick I agree that #346 would solve for this. I vote to go for that approach

2022-03-25 09:39 UTC, oliverroick commented
Ok, TOC + back to top links it is

2022-03-25 09:39 UTC, closed without merging