Add table numbers
NASA-IMPACT/nasa-apt-frontend pull request #549
Opened 2023-10-03 13:48 UTC by vgeorge

Fix https://github.com/NASA-IMPACT/nasa-apt/issues/681.

Before generating the PDFs, apply `formatDocumentTableCaptions()` to the document in order to compute table numbers and move the caption before the table.

To test, run the app locally using the staging API and visit:

- http://localhost:9000/documents/test/v1.0/pdf-preview
- http://localhost:9000/documents/test/v1.0/journal-pdf-preview

Or create a new document with tables in different sections.

2023-10-03 13:50 UTC, vgeorge commented
@kamicut this is ready for review.

cc @wrynearson

2023-10-03 15:21 UTC, kamicut commented
Hey @vgeorge thanks for this PR, here are my comments:

1. I think the requirements need the table caption to be left-aligned, cc @wrynearson 
2. I like what you did with the transform, however I feel that it's not "abstractable" in case we have multiple transforms. I would maybe create a "transform" function that takes a list of functions and applies the transforms to the document before the rendering. However, this might be optimizing too early, let me know what you think?

```js
const docTransforms = [formatDocumentTableCaptions]

function transform(document) {
 return docTransforms.reduce((curDoc, curFn) => curFn(curDoc), document)
}
```

2023-10-03 15:22 UTC, kamicut requested changes
I've made some comments in the thread

2023-10-04 09:41 UTC, wrynearson approved these changes
LGTM!

2023-10-04 09:54 UTC, merged

2023-10-04 09:59 UTC, vgeorge commented
@kamicut @wrynearson thanks for the review! I didn't aligned to the left first because images were center-aligned. My last commit made all captions to aligned left. Later we need to confirm if images also need to be aligned to the left and apply a fix if they don't. About the transform refactor, it should be straightforward to concatenate additional transforms later if needed.

2023-10-04 11:16 UTC, wrynearson commented
Good point @vgeorge, thanks. @bwbaker1 – can you confirm if images in `journal` and `document` PDF should be centered or left-justified?

FWIW, images in the PDF documents _should_ fill the full width, so the justification wouldn't matter much.

2023-10-04 14:12 UTC, bwbaker1 commented
@wrynearson @vgeorge Good catch! I think it should be left-justified. My reasoning is so that the image and caption align. See the image and notice the alignment is slightly off.

<img width="961" alt="Screen Shot 2023-10-04 at 9 04 36 AM" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/56319064/04711869-e5f3-45b7-9757-0af9fd5aa867">